"""Serializable architecture model shared by the inspector and Spyder UI."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


NodeKind = Literal[
    "route",
    "parameter",
    "model",
    "dependency",
    "handler",
]
DiagramNodeKind = Literal[
    "route",
    "parameter",
    "model",
    "dependency",
    "handler",
    "test",
    "database",
    "http-client",
    "messaging",
    "rpc",
    "external",
]
DiagramEvidenceKind = Literal["contract", "test", "runtime"]


class SourceRef(BaseModel):
    """Location of a Python callable in source code when it can be resolved."""

    file: str | None = None
    line: int | None = None
    execution_line: int | None = None
    qualname: str | None = None


class AppCandidate(BaseModel):
    """Statically discovered FastAPI application target."""

    target: str
    module: str
    attribute: str
    source: SourceRef


class ParameterSpec(BaseModel):
    """One request parameter accepted by a route or dependency."""

    name: str
    alias: str | None = None
    location: Literal["path", "query", "header", "cookie", "body"]
    type_name: str
    required: bool


class DependencySpec(BaseModel):
    """A FastAPI dependency and its nested dependencies."""

    id: str
    name: str
    source: SourceRef
    use_cache: bool = True
    scope: str | None = None
    parameters: list[ParameterSpec] = Field(default_factory=list)
    children: list[str] = Field(default_factory=list)


class ModelSpec(BaseModel):
    """OpenAPI schema generated by FastAPI/Pydantic."""

    name: str
    source: SourceRef | None = None
    field_sources: dict[str, SourceRef] = Field(default_factory=dict)
    schema_: dict[str, Any] = Field(default_factory=dict, alias="schema")

    model_config = {"populate_by_name": True}


class RouteSpec(BaseModel):
    """Normalized representation of one HTTP operation."""

    id: str
    method: str
    path: str
    name: str
    handler: str
    source: SourceRef
    status_code: int | None = None
    tags: list[str] = Field(default_factory=list)
    parameters: list[ParameterSpec] = Field(default_factory=list)
    request_models: list[str] = Field(default_factory=list)
    response_model: str | None = None
    dependencies: list[str] = Field(default_factory=list)


class LineageNode(BaseModel):
    """Node in the deterministic FastAPI contract/dependency lineage graph."""

    id: str
    kind: NodeKind
    label: str
    route_id: str | None = None
    source: SourceRef | None = None


class LineageEdge(BaseModel):
    """Directed relationship in the lineage graph."""

    source: str
    target: str
    relation: Literal[
        "accepts",
        "validates_as",
        "depends_on",
        "contains",
        "handled_by",
        "returns",
    ]


class LineageGraph(BaseModel):
    """FastAPI graph usable by a GUI without importing Qt or Spyder."""

    nodes: list[LineageNode] = Field(default_factory=list)
    edges: list[LineageEdge] = Field(default_factory=list)


class FastAPIMap(BaseModel):
    """Stable JSON bridge between FastAPI runtime inspection and the Spyder UI."""

    title: str
    version: str | None = None
    openapi_version: str
    openapi: dict[str, Any] = Field(default_factory=dict)
    routes: list[RouteSpec]
    dependencies: list[DependencySpec]
    models: list[ModelSpec]
    lineage: LineageGraph

ChangeEntity = Literal["route", "model", "dependency"]
ChangeKind = Literal["added", "removed", "changed"]


class SemanticChange(BaseModel):
    """One meaningful contract or architecture change between two snapshots."""

    entity: ChangeEntity
    name: str
    kind: ChangeKind
    fields: list[str] = Field(default_factory=list)
    affected_routes: list[str] = Field(default_factory=list)
    breaking_reasons: list[str] = Field(default_factory=list)
    source: SourceRef | None = None


class APIDiff(BaseModel):
    """Semantic difference between two FastAPI architecture snapshots."""

    changes: list[SemanticChange] = Field(default_factory=list)
    affected_routes: list[str] = Field(default_factory=list)
    breaking_candidates: int = 0


class SnapshotEnvelope(BaseModel):
    """Versioned on-disk FastAPI Studio snapshot."""

    format_version: int = 1
    target: str | None = None
    trace_id: str | None = None
    api: FastAPIMap


RequestLocation = Literal["path", "query", "header", "cookie", "body"]


class RequestField(BaseModel):
    """One editable input in the generated Request Lab form."""

    name: str
    python_name: str | None = None
    location: RequestLocation
    type_name: str
    required: bool
    example: Any = None
    description: str | None = None
    source: SourceRef | None = None
    is_file: bool = False
    multiple: bool = False
    media_type: str | None = None


class RequestTemplate(BaseModel):
    """Generated request form for one FastAPI route."""

    route_id: str
    method: str
    path: str
    parameters: list[RequestField] = Field(default_factory=list)
    body_example: Any = None
    body_required: bool = False
    body_content_type: str | None = None
    body_model: str | None = None
    body_source: SourceRef | None = None
    body_fields: list[RequestField] = Field(default_factory=list)


class ValidationIssue(BaseModel):
    """Structured FastAPI/Pydantic validation issue from a 422 response."""

    location: str
    field_path: str
    message: str
    error_type: str
    expected_type: str | None = None
    input_value: Any = None
    source: SourceRef | None = None


class RequestExecution(BaseModel):
    """Serializable result returned by the isolated request subprocess."""

    url: str
    status_code: int | None = None
    reason: str | None = None
    headers: dict[str, str] = Field(default_factory=dict)
    text: str = ""
    json_body: Any = None
    elapsed_ms: float | None = None
    error: str | None = None

class RouteTestReference(BaseModel):
    """Statically observed HTTP call from a project test to a FastAPI route."""

    id: str
    route_id: str
    test_name: str
    method: str
    requested_path: str
    match_kind: Literal["exact", "template"]
    source: SourceRef
    call_line: int | None = None


class RouteTestIndex(BaseModel):
    """Project-local static route-to-test links."""

    references: list[RouteTestReference] = Field(default_factory=list)
    scanned_files: int = 0


class DiagramNode(BaseModel):
    """Presentation-neutral node used by FastAPI architecture diagrams."""

    id: str
    kind: DiagramNodeKind
    label: str
    source: SourceRef | None = None
    route_id: str | None = None
    impact_count: int = 0
    evidence: DiagramEvidenceKind = "contract"
    observed_count: int = 0
    average_ms: float | None = None
    p95_ms: float | None = None
    last_ms: float | None = None
    target: str | None = None


class DiagramEdge(BaseModel):
    """Directed diagram relationship after optional graph compaction."""

    source: str
    target: str
    relation: str


class DiagramProjection(BaseModel):
    """Headless graph projection rendered by the Spyder Qt diagram view."""

    mode: Literal["route", "global", "impact"]
    title: str
    roots: list[str] = Field(default_factory=list)
    nodes: list[DiagramNode] = Field(default_factory=list)
    edges: list[DiagramEdge] = Field(default_factory=list)
    focus_id: str | None = None


class RouteRuntimeStats(BaseModel):
    """Observed Request Lab timing/status evidence for one FastAPI route."""

    route_id: str
    request_count: int = 0
    timed_count: int = 0
    last_elapsed_ms: float | None = None
    average_elapsed_ms: float | None = None
    min_elapsed_ms: float | None = None
    max_elapsed_ms: float | None = None
    last_status_code: int | None = None
    transport_error_count: int = 0


class RuntimeEvidence(BaseModel):
    """In-memory route runtime evidence collected by Request Lab."""

    routes: dict[str, RouteRuntimeStats] = Field(default_factory=dict)


class NativeTelemetrySpan(BaseModel):
    """Normalized OpenTelemetry span captured from the local FastAPI server."""

    signal: Literal["span"] = "span"
    schema_version: int = 1
    trace_id: str
    span_id: str
    parent_span_id: str | None = None
    name: str
    kind: str
    start_ns: int
    end_ns: int
    duration_ms: float
    status: str | None = None
    attributes: dict[str, Any] = Field(default_factory=dict)
    scope_name: str | None = None
    scope_version: str | None = None


class NativeTelemetryLog(BaseModel):
    """Normalized OpenTelemetry log/event captured from FastAPI."""

    signal: Literal["log"] = "log"
    schema_version: int = 1
    timestamp_ns: int | None = None
    observed_timestamp_ns: int | None = None
    trace_id: str | None = None
    span_id: str | None = None
    severity: str | None = None
    event_name: str | None = None
    body: str | None = None
    attributes: dict[str, Any] = Field(default_factory=dict)
    exception_type: str | None = None
    scope_name: str | None = None


class NativeTelemetryControl(BaseModel):
    """Lifecycle/status record for the local native telemetry capture."""

    signal: Literal["control"] = "control"
    schema_version: int = 1
    event: str
    message: str | None = None
    fastapi_version: str | None = None
    tracing: bool | None = None
    logs: bool | None = None


class NativeRouteTelemetry(BaseModel):
    """Aggregated native server-span metrics for one FastAPI route."""

    route_id: str
    request_count: int = 0
    error_count: int = 0
    error_rate: float = 0.0
    validation_failure_count: int = 0
    average_ms: float | None = None
    p50_ms: float | None = None
    p95_ms: float | None = None
    min_ms: float | None = None
    max_ms: float | None = None
    last_ms: float | None = None
    last_status_code: int | None = None

