"""Serializable architecture model shared by the inspector and Spyder UI."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


NodeKind = Literal[
    "route",
    "parameter",
    "model",
    "dependency",
    "handler",
]


class SourceRef(BaseModel):
    """Location of a Python callable in source code when it can be resolved."""

    file: str | None = None
    line: int | None = None
    execution_line: int | None = None
    qualname: str | None = None


class AppCandidate(BaseModel):
    """Statically discovered FastAPI application target."""

    target: str
    module: str
    attribute: str
    source: SourceRef


class ParameterSpec(BaseModel):
    """One request parameter accepted by a route or dependency."""

    name: str
    alias: str | None = None
    location: Literal["path", "query", "header", "cookie", "body"]
    type_name: str
    required: bool


class DependencySpec(BaseModel):
    """A FastAPI dependency and its nested dependencies."""

    id: str
    name: str
    source: SourceRef
    use_cache: bool = True
    scope: str | None = None
    parameters: list[ParameterSpec] = Field(default_factory=list)
    children: list[str] = Field(default_factory=list)


class ModelSpec(BaseModel):
    """OpenAPI schema generated by FastAPI/Pydantic."""

    name: str
    source: SourceRef | None = None
    field_sources: dict[str, SourceRef] = Field(default_factory=dict)
    schema_: dict[str, Any] = Field(default_factory=dict, alias="schema")

    model_config = {"populate_by_name": True}


class RouteSpec(BaseModel):
    """Normalized representation of one HTTP operation."""

    id: str
    method: str
    path: str
    name: str
    handler: str
    source: SourceRef
    status_code: int | None = None
    tags: list[str] = Field(default_factory=list)
    parameters: list[ParameterSpec] = Field(default_factory=list)
    request_models: list[str] = Field(default_factory=list)
    response_model: str | None = None
    dependencies: list[str] = Field(default_factory=list)


class LineageNode(BaseModel):
    """Node in the deterministic FastAPI contract/dependency lineage graph."""

    id: str
    kind: NodeKind
    label: str
    route_id: str | None = None
    source: SourceRef | None = None


class LineageEdge(BaseModel):
    """Directed relationship in the lineage graph."""

    source: str
    target: str
    relation: Literal[
        "accepts",
        "validates_as",
        "depends_on",
        "contains",
        "handled_by",
        "returns",
    ]


class LineageGraph(BaseModel):
    """FastAPI graph usable by a GUI without importing Qt or Spyder."""

    nodes: list[LineageNode] = Field(default_factory=list)
    edges: list[LineageEdge] = Field(default_factory=list)


class FastAPIMap(BaseModel):
    """Stable JSON bridge between FastAPI runtime inspection and the Spyder UI."""

    title: str
    version: str | None = None
    openapi_version: str
    openapi: dict[str, Any] = Field(default_factory=dict)
    routes: list[RouteSpec]
    dependencies: list[DependencySpec]
    models: list[ModelSpec]
    lineage: LineageGraph

ChangeEntity = Literal["route", "model", "dependency"]
ChangeKind = Literal["added", "removed", "changed"]


class SemanticChange(BaseModel):
    """One meaningful contract or architecture change between two snapshots."""

    entity: ChangeEntity
    name: str
    kind: ChangeKind
    fields: list[str] = Field(default_factory=list)
    affected_routes: list[str] = Field(default_factory=list)
    breaking_reasons: list[str] = Field(default_factory=list)
    source: SourceRef | None = None


class APIDiff(BaseModel):
    """Semantic difference between two FastAPI architecture snapshots."""

    changes: list[SemanticChange] = Field(default_factory=list)
    affected_routes: list[str] = Field(default_factory=list)
    breaking_candidates: int = 0


class SnapshotEnvelope(BaseModel):
    """Versioned on-disk FastAPI Studio snapshot."""

    format_version: int = 1
    target: str | None = None
    api: FastAPIMap


RequestLocation = Literal["path", "query", "header", "cookie", "body"]


class RequestField(BaseModel):
    """One editable input in the generated Request Lab form."""

    name: str
    python_name: str | None = None
    location: RequestLocation
    type_name: str
    required: bool
    example: Any = None
    description: str | None = None
    source: SourceRef | None = None
    is_file: bool = False
    multiple: bool = False
    media_type: str | None = None


class RequestTemplate(BaseModel):
    """Generated request form for one FastAPI route."""

    route_id: str
    method: str
    path: str
    parameters: list[RequestField] = Field(default_factory=list)
    body_example: Any = None
    body_required: bool = False
    body_content_type: str | None = None
    body_model: str | None = None
    body_source: SourceRef | None = None
    body_fields: list[RequestField] = Field(default_factory=list)


class ValidationIssue(BaseModel):
    """Structured FastAPI/Pydantic validation issue from a 422 response."""

    location: str
    field_path: str
    message: str
    error_type: str
    expected_type: str | None = None
    input_value: Any = None
    source: SourceRef | None = None


class RequestExecution(BaseModel):
    """Serializable result returned by the isolated request subprocess."""

    url: str
    status_code: int | None = None
    reason: str | None = None
    headers: dict[str, str] = Field(default_factory=dict)
    text: str = ""
    json_body: Any = None
    elapsed_ms: float | None = None
    error: str | None = None

class DiagramNode(BaseModel):
    """Presentation-neutral node used by FastAPI architecture diagrams."""

    id: str
    kind: NodeKind
    label: str
    source: SourceRef | None = None
    route_id: str | None = None
    impact_count: int = 0


class DiagramEdge(BaseModel):
    """Directed diagram relationship after optional graph compaction."""

    source: str
    target: str
    relation: str


class DiagramProjection(BaseModel):
    """Headless graph projection rendered by the Spyder Qt diagram view."""

    mode: Literal["route", "global", "impact"]
    title: str
    roots: list[str] = Field(default_factory=list)
    nodes: list[DiagramNode] = Field(default_factory=list)
    edges: list[DiagramEdge] = Field(default_factory=list)
    focus_id: str | None = None

