"""Serializable architecture model shared by the inspector and Spyder UI."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


NodeKind = Literal[
    "route",
    "parameter",
    "model",
    "dependency",
    "handler",
]


class SourceRef(BaseModel):
    """Location of a Python callable in source code when it can be resolved."""

    file: str | None = None
    line: int | None = None
    qualname: str | None = None


class ParameterSpec(BaseModel):
    """One request parameter accepted by a FastAPI route."""

    name: str
    location: Literal["path", "query", "header", "cookie", "body"]
    type_name: str
    required: bool


class DependencySpec(BaseModel):
    """A FastAPI dependency and its nested dependencies."""

    id: str
    name: str
    source: SourceRef
    use_cache: bool = True
    scope: str | None = None
    children: list[str] = Field(default_factory=list)


class ModelSpec(BaseModel):
    """OpenAPI schema generated by FastAPI/Pydantic."""

    name: str
    schema_: dict[str, Any] = Field(default_factory=dict, alias="schema")

    model_config = {"populate_by_name": True}


class RouteSpec(BaseModel):
    """Normalized representation of one HTTP operation."""

    id: str
    method: str
    path: str
    name: str
    handler: str
    source: SourceRef
    status_code: int | None = None
    tags: list[str] = Field(default_factory=list)
    parameters: list[ParameterSpec] = Field(default_factory=list)
    request_models: list[str] = Field(default_factory=list)
    response_model: str | None = None
    dependencies: list[str] = Field(default_factory=list)


class LineageNode(BaseModel):
    """Node in the deterministic FastAPI contract/dependency lineage graph."""

    id: str
    kind: NodeKind
    label: str
    route_id: str | None = None
    source: SourceRef | None = None


class LineageEdge(BaseModel):
    """Directed relationship in the lineage graph."""

    source: str
    target: str
    relation: Literal[
        "accepts",
        "validates_as",
        "depends_on",
        "contains",
        "handled_by",
        "returns",
    ]


class LineageGraph(BaseModel):
    """FastAPI graph usable by a GUI without importing Qt or Spyder."""

    nodes: list[LineageNode] = Field(default_factory=list)
    edges: list[LineageEdge] = Field(default_factory=list)


class FastAPIMap(BaseModel):
    """Stable JSON bridge between FastAPI runtime inspection and the Spyder UI."""

    title: str
    version: str | None = None
    openapi_version: str
    routes: list[RouteSpec]
    dependencies: list[DependencySpec]
    models: list[ModelSpec]
    lineage: LineageGraph
